apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  namespace: vault
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
