apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    app: vault
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8200
  type: {{ .Values.service.type }}
